### ISSUE TITLE
Information on RAG: fragments shown similar to system prompts

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter-next#22]
The app already has a modal with a little widget in the conversation to see the system prompts that are used (screenshot, "With 3 contextual prompts").

![Image](https://github.com/biocypher/chatgse-next/assets/13223629/b08beb20-fdbe-46b9-93c5-215ae0955d30)

We could have a similar widget that leads to a `RAG - used fragments` modal to inform the user which information was used in the last (or all previous) responses from the model, could be called "With X RAG prompts".

**Comment by fengsh27** [comment]
Done by submission 414ee0dc354a3d4b79403e40d7a2d773f6cabb1c
