### ISSUE TITLE
Separate page for knowledge graphs

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter-next#3]
Similar to the "Mask" page in the original, have a "Knowledge Graph" page that shows

- on/off button for KG connect
- connection settings
- indication of successful connection and schema_info loading
- authentication
- simple isolated chat to generate and run a query on the connected graph

Use a return button to get back to the main conversation

If a KG is connected, have a small button at the conversation input to activate the KG for the question to be asked

**Comment by agdiaz** [comment]
The small button will be placed next to the model selection:

<img width="900" alt="image" src="https://github.com/biocypher/chatgse-next/assets/1646576/68317c7b-6493-41ab-af37-4d316326014e">
