### ISSUE TITLE
Update readme in `biochatter-next` folder

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter-next#45]
As per request from Qin Ma.

**Comment by slobentanzer** [comment]
@fengsh27, should we maybe migrate the entire biochatter-next one folder up, so it is in root? There is no real reason any more to keep it in a subfolder, is there?

**Comment by slobentanzer** [comment]
Would then of course also use a BioChatter-specific README as opposed to the ChatGPT-Next one.

**Comment by fengsh27** [comment]
Yes, it makes sense to remove the subfolder.

**Comment by slobentanzer** [comment]
Closed by #60
