### ISSUE TITLE
More feedback from next app regarding KG

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter-next#56]
It would be nice to see more information in the KG Settings, for instance the schema as in the BioChatter light implementation. I tried to replace the pole KG with another small KG (https://hub.docker.com/r/biocypher/drug-interactions), but for some reason the KG RAG does not work (not returning answer or not using the KG, no KG query metadata shown as result).

It would be a nice sanity check to see the information of the connected graph in the Next app. The Neo4j browser version of the graph works fine. I just changed one line in the compose from the current `main` of `biochatter-next`:

```
  biocypher:
    container_name: biocypher
    image: biocypher/drug-interactions:0.1.1
```

@fengsh27, maybe you could check that on your machine and let me know what you find?

**Comment by fengsh27** [comment]
@slobentanzer , I tried image drug-interactions. BioChatter succeeded to connect to graph database. What questions should I use to test the knowledge graph? Let me try it in biochatter's unit test directly.

**Comment by slobentanzer** [comment]
Hi @fengsh27,
Thanks, I also managed to connect, but then did not get an answer. I think BioChatter is well-covered by unit tests and the benchmark, I don't think the issue lies there. My general problem is the intransparency caused by the multiple moving parts of the server and next app, which I can't really debug very well. In the medium term we should definitely extend test coverage on these two parts, and I think an API docs (https://github.com/orgs/biocypher/projects/1/views/11?pane=issue&itemId=49173103) would also be great for testing/debugging.

I can take care of the BioChatter side, could you debug the BioChatter Next side? You can use questions like "Does dexamethasone interact with acetylsalicylic acid?", for instance (or anything else about drug interactions). Even questions like "How many drugs are in the database?" should work out of the box, as they do with pole.

The issue I have, more specifically, is that the KG is connected (and activated of course), but then there is an empty response:
<img width="974" alt="Screenshot 2024-03-01 at 10 39 24" src="https://github.com/biocypher/biochatter-next/assets/13223629/b4d06fd7-2b44-42cf-8c0b-e5538deb2a7e">

In addition, the bottom menu shows "With 0 RAG prompts", not even KG prompts, which I find weird:
<img width="398" alt="Screenshot 2024-03-01 at 10 39 32" src="https://github.com/biocypher/biochatter-next/assets/13223629/54cc1ef0-b7b7-4d36-951d-a62629638974">

Maybe it would be better / more transparent to have two buttons for the RAG and KG prompts? Anyway, would be great if you could look into that. :)

**Comment by fengsh27** [comment]
@slobentanzer , I have update KG of [our server](https://bmblx.bmi.osumc.edu/biochatter-next) to drug-interactions image. For question "how many drugs are in the database?", it works fine:
![image](https://github.com/biocypher/biochatter-next/assets/123769183/397034df-069c-46f7-95fd-aba209b6532f)

For question "Does dexamethasone interact with acetylsalicylic acid?", no KG result was found, see below picture:
![image](https://github.com/biocypher/biochatter-next/assets/123769183/7a8cdd60-e227-40a2-8d49-411eaf11c61b)

Here is from biochatter-server logs:
```
2024-03-01 08:54:51 - biochatter.llm_connect - WARNING - No entities found. Please run the entity selection step first.
```

**Comment by slobentanzer** [comment]
Hi @fengsh27,
thanks. I am not sure updating the online version is the right way to go, as the vignette currently explains the Pole graph, and reviewers may be confused if they check that. I would revert it to the pole graph.

Generally, regarding the Next app:
- it would be great to let the user know that the query failed (for whatever reason). So, if we get a non-result, just let the user know; maybe even prevent an LLM answer but rather show a "Query not successful" message and give the user a chance to improve (similar to the old implementation of the BioChatter Light app, where the query can even be manually edited by the user).
- it seems that the button with "RAG prompts" and "KG prompts" defaults to "RAG" even if the user chose "KG", which is a bit confusing. I think a two-button solution would be easiest, but happy for other suggestions. :)

What do you think? And do you have time to address these?

**Comment by fengsh27** [comment]
@slobentanzer , Sure, I'll revert KG back to pole.

**Comment by slobentanzer** [comment]
BTW, why did you update the online version? Can you run it locally, or does that not work for you either?

**Comment by fengsh27** [comment]
The local version works in my machine, I just want to show it to you, this is the fastest way.

**Comment by slobentanzer** [comment]
Let's talk further on Zulip :)

**Comment by fengsh27** [comment]
> What do you think? And do you have time to address these?

I'll manage to address it.
